version: 2
updates:
  # Flutter/Dart dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "nikitiser"
    assignees:
      - "nikitiser"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"

  # Example app dependencies
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "nikitiser"
    assignees:
      - "nikitiser"
    commit-message:
      prefix: "deps(example)"
      include: "scope"
    labels:
      - "dependencies"
      - "example"
      - "automated"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "nikitiser"
    assignees:
      - "nikitiser"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
