name: ✨ Feature Request
description: Suggest an idea for the weight scale plugin
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees:
  - nikitiser

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨

  - type: textarea
    id: problem
    attributes:
      label: 🤔 Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: 💡 Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Really need this
        - Critical - Blocking my use case
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 📱 Platform
      description: Which platform would this feature target?
      options:
        - Android (current)
        - iOS (future)
        - All platforms
        - Plugin architecture
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: 🎯 Use Case
      description: Provide a detailed use case for this feature
      placeholder: |
        In my application, users need to...
        This would help by...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 🛠️ Implementation Ideas
      description: If you have ideas on how this could be implemented, please share them
      placeholder: This could be implemented by...

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Context
      description: Add any other context, mockups, or examples about the feature request here

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: This feature aligns with the plugin's scope (weight scale communication)
          required: true
